apiVersion: v1
kind: Service
metadata:
  name: price-api-service-nodeport
  namespace: price-api
  labels:
    app: price-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: price-api